# Generated by Django 4.2.4 on 2023-08-03 16:00

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artilharia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero_de_equipes', models.IntegerField()),
                ('formato', models.CharField(choices=[('PONTOS_CORRIDOS', 'Pontos corridos'), ('GRUPOS_MATA_MATA', 'Grupos + Mata-Mata'), ('MATA_MATA', 'Mata-Mata')], max_length=30)),
                ('visualizacoes', models.IntegerField()),
                ('jogos_ida_e_volta', models.CharField(max_length=5)),
                ('tipo_competidor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quant_atletas', models.IntegerField()),
                ('resultados', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=30)),
                ('data_nascimento', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('gols', models.IntegerField()),
                ('assistencias', models.IntegerField()),
                ('RG_CPF', models.CharField(max_length=15)),
                ('artilharia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artilheiro', to='campeonato.artilharia')),
                ('assistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistente', to='campeonato.assistente')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_do_jogador', to='campeonato.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('meus_campeonatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_campeonatos', to='campeonato.campeonato')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('jogos', models.IntegerField()),
                ('gols_feitos', models.IntegerField()),
                ('gols_sofridos', models.IntegerField()),
                ('cartoes_amarelos', models.IntegerField()),
                ('cartoes_vermelhos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('aproveitamento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_do_campeonato', to='campeonato.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar', models.CharField(max_length=30)),
                ('cartoes_amarelos', models.IntegerField()),
                ('cartoes_vermelhos', models.IntegerField()),
                ('horario', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('assistentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passador', to='campeonato.jogador')),
                ('equipe_mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='campeonato.equipe')),
                ('equipe_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='campeonato.equipe')),
                ('marcadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcador', to='campeonato.jogador')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_da_equipe', to='campeonato.tabela'),
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateTimeField()),
                ('RG_CPF', models.CharField(max_length=15)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_da_comissao', to='campeonato.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='campeonato',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to='campeonato.usuario'),
        ),
        migrations.AddField(
            model_name='assistente',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistentes', to='campeonato.tabela'),
        ),
        migrations.AddField(
            model_name='artilharia',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artilheiros', to='campeonato.tabela'),
        ),
    ]
