# Generated by Django 4.2.4 on 2023-08-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogos',
            new_name='Jogo',
        ),
    ]
