# Generated by Django 4.2.4 on 2023-08-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_rename_jogos_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='artilharia',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='assistente',
        ),
        migrations.AddField(
            model_name='artilharia',
            name='jogador',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_artilheiro', to='campeonato.jogador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistente',
            name='jogador',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_assistente', to='campeonato.jogador'),
            preserve_default=False,
        ),
    ]
