# Generated by Django 4.2.4 on 2023-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_remove_jogador_artilharia_remove_jogador_assistente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artilharia',
            name='jogador',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='jogador',
        ),
        migrations.AddField(
            model_name='artilharia',
            name='jogador_artilheiro',
            field=models.ManyToManyField(to='campeonato.jogador'),
        ),
        migrations.AddField(
            model_name='assistente',
            name='jogador_assistente',
            field=models.ManyToManyField(to='campeonato.jogador'),
        ),
    ]
