# Generated by Django 4.2.4 on 2023-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_remove_artilharia_jogador_remove_assistente_jogador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artilharia',
            old_name='jogador_artilheiro',
            new_name='jogador_artilheiro_campeonato',
        ),
        migrations.RenameField(
            model_name='assistente',
            old_name='jogador_assistente',
            new_name='jogador_assistente_campeonato',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='assistentes',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='marcadores',
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogador_assistente_jogo',
            field=models.ManyToManyField(related_name='passador_no_jogo', to='campeonato.jogador'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='jogador_marcador_jogo',
            field=models.ManyToManyField(related_name='marcador_no_jogo', to='campeonato.jogador'),
        ),
    ]
