# Generated by Django 4.2.2 on 2023-08-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0008_alter_usuario_meus_campeonatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artilharia',
            name='gols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artilharia',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artilheiros', to='campeonato.tabela'),
        ),
        migrations.AlterField(
            model_name='assistente',
            name='assistencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistente',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistentes', to='campeonato.tabela'),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='visualizacoes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='resultados',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabela_da_equipe', to='campeonato.tabela'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='assistencias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='gols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_amarelos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_vermelhos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='horario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogador_assistente_jogo',
            field=models.ManyToManyField(blank=True, null=True, related_name='passador_no_jogo', to='campeonato.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogador_marcador_jogo',
            field=models.ManyToManyField(blank=True, null=True, related_name='marcador_no_jogo', to='campeonato.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='local',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='cartoes_amarelos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='cartoes_vermelhos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='derrotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='empates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='gols_feitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='gols_sofridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='jogos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='vitorias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
