# Generated by Django 4.2.2 on 2023-08-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0009_alter_artilharia_gols_alter_artilharia_tabela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
