# Generated by Django 4.2.2 on 2023-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0010_alter_jogador_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
