# Generated by Django 4.2.2 on 2023-08-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0011_alter_comissao_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to='campeonato.equipe'),
        ),
    ]
