# Generated by Django 4.2.2 on 2023-08-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0012_alter_jogador_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='formato',
            field=models.CharField(max_length=30),
        ),
    ]
