# Generated by Django 4.2.2 on 2023-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0013_alter_campeonato_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='cartoes_amarelos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='cartoes_vermelhos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='derrotas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='empates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='gols_feitos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='gols_sofridos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='jogos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='pontos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='vitorias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
