# Generated by Django 4.2.2 on 2023-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0014_alter_tabela_cartoes_amarelos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='aproveitamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
