# Generated by Django 4.2.2 on 2023-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0015_alter_tabela_aproveitamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='meus_campeonatos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='meus_campeonatos',
            field=models.ManyToManyField(null=True, related_name='meus_campeonatos', to='campeonato.campeonato'),
        ),
    ]
