# Generated by Django 4.2.2 on 2023-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0016_remove_usuario_meus_campeonatos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipe_participante', to='campeonato.equipe'),
        ),
    ]
