# Generated by Django 4.2.2 on 2023-08-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0019_remove_equipe_tabela_equipe_tabela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='tabela',
        ),
    ]
