# Generated by Django 4.2.2 on 2023-08-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0020_remove_equipe_tabela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='time',
            new_name='equipe',
        ),
    ]
