# Generated by Django 4.2.2 on 2023-08-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0021_rename_time_tabela_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela',
            name='equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabela_da_equipe', to='campeonato.tabela'),
        ),
    ]
