# Generated by Django 4.2.2 on 2023-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0022_remove_tabela_equipe_equipe_tabela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='aproveitamento',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='cartoes_amarelos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='cartoes_vermelhos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='empates',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='gols_feitos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='gols_sofridos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='jogos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='tabela',
            name='vitorias',
        ),
        migrations.AddField(
            model_name='equipe',
            name='aproveitamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='equipe',
            name='cartoes_amarelos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='cartoes_vermelhos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='derrotas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='empates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='gols_feitos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='gols_sofridos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='jogos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='pontos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='vitorias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
