# Generated by Django 4.2.2 on 2023-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0023_remove_equipe_resultados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='quant_atletas',
        ),
    ]
