# Generated by Django 4.2.2 on 2023-08-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0024_remove_equipe_quant_atletas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artilharia',
            name='tabela',
        ),
        migrations.RemoveField(
            model_name='assistente',
            name='tabela',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='tabela',
        ),
        migrations.AddField(
            model_name='artilharia',
            name='tabela_artilheiros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artilheiros', to='campeonato.campeonato'),
        ),
        migrations.AddField(
            model_name='assistente',
            name='tabela_assistentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistentes', to='campeonato.campeonato'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato', to='campeonato.campeonato'),
        ),
        migrations.DeleteModel(
            name='Tabela',
        ),
    ]
