# Generated by Django 4.2.2 on 2023-08-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0026_alter_equipe_campeonato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='RG_CPF',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='RG_CPF',
        ),
    ]
