# Generated by Django 4.2.2 on 2023-08-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0027_remove_comissao_rg_cpf_remove_jogador_rg_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='campeonato.equipe'),
        ),
    ]
