# Generated by Django 4.2.2 on 2023-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0028_alter_jogador_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='jogador_assistente_jogo',
            field=models.ManyToManyField(blank=True, related_name='passador_no_jogo', to='campeonato.jogador'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogador_marcador_jogo',
            field=models.ManyToManyField(blank=True, related_name='marcador_no_jogo', to='campeonato.jogador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meus_campeonatos',
            field=models.ManyToManyField(related_name='meus_campeonatos', to='campeonato.campeonato'),
        ),
    ]
