# Generated by Django 4.2.2 on 2023-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0029_alter_jogo_jogador_assistente_jogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='aproveitamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
